### ISSUE TITLE
Injection failed with unknown error

### ISSUE THREAD

**Issue by Arkshine** [mcoot/TribesLauncher#2]
Hi, 

Today, I noticed TAMods was not working. I updated it, and even reinstalled through the whole  the UI, but even though it was saying injection was done, nothing happened in game.

So I wanted to reinstall the whole package and found TribesLauncher.
I've installed it, and then upated TAMods from the button.

This is the current settings:

![image](https://user-images.githubusercontent.com/360640/43732048-bf45ba7a-99b0-11e8-82d1-929cd28d3359.png)

![image](https://user-images.githubusercontent.com/360640/43731947-6cf754ea-99b0-11e8-8ff9-605b066cc595.png)

![image](https://user-images.githubusercontent.com/360640/43731980-8be7079c-99b0-11e8-8727-c6cbf447a495.png)

When I launch the game from the button, at some point, it asks persmission to execute the .exe and after that I get the following error:

![image](https://user-images.githubusercontent.com/360640/43732156-199ff878-99b1-11e8-8760-f03fb7251fc7.png)

This is under Windows 7 SP1.

**Comment by ToddButler93** [comment]
I believe this is still due to the use of XAUDIO2, on the SDK we compile with it doesn't contain headers for xaudio 2.7 which is the last one that was shipped for Windows 7. Give this DLL a try: https://nofile.io/f/CqxGVxcHfgc/TAMods.dll

**Comment by Arkshine** [comment]
Yep, it's working now. Thanks!
